Output ./assets/demo.gif

Set Theme {"name": "Custom", "black": "#010409", "red": "#f8f8f8", "green": "#f8f8f8", "yellow": "#f8f8f8", "blue": "#f8f8f8", "magenta": "#f8f8f8", "cyan": "#f8f8f8", "white": "#f8f8f8", "brightBlack": "#010409", "brightRed": "#f8f8f8", "brightGreen": "#f8f8f8", "brightYellow": "#f8f8f8", "brightBlue": "#f8f8f8", "brightMagenta": "#f8f8f8", "brightCyan": "#f8f8f8", "brightWhite": "#f8f8f8", "background": "#010409", "foreground": "#f8f8f8", "cursor": "#f8f8f8"}
Set Shell "zsh"
Set Width 1500
Set Height 775

Env PS1 "> "

Type "cargo run -q"
Enter
Sleep 3s
Enter
Sleep 2s
Down@200ms 2
Sleep 2s
Space
Sleep 2s
Enter
Sleep 2s
Type@100ms "The House I Live In"
Sleep 1
Enter
Wait+Screen /Select:/
Sleep 3s
Enter
Sleep 3s
Enter
Sleep 10s
